#{"swagger":"2.0","info":{"description":"Api Documentation","version":"1.0","title":"Api Documentation","termsOfService":"urn:tos","contact":{},"license":{"name":"Apache 2.0","url":"http://www.apache.org/licenses/LICENSE-2.0"}},"host":"test7-186023.appspot.com","basePath":"/HelloWS","tags":[{"name":"hello-controller","description":"WS to test"}],"paths":{"/hello":{"get":{"tags":["hello-controller"],"summary":"Says hello","operationId":"indexUsingGET","consumes":["application/json"],"produces":["text/plain"],"responses":{"200":{"description":"OK","schema":{"type":"string"}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}}}}}}

swagger: "2.0"
info: 
    description: "A hello WS"
    version: "1.0"
    title: "Hello WS"
host: "test7-186023.appspot.com"

basePath: "/HelloWS"
tags:
-   name: "hello-controller"
    description: "WS to test"
paths:
    "/hello": 
        get:
            description: "Says hello"
            operationId: "saysHello"
            produces: 
                - "text/plain"
            responses: 
                200: 
                    description: OK
                401: 
                    description: Unauthorized
                403: 
                    description: Forbidden
                404: 
                    description: "Not Found"